import { hash as argon2Hash, verify as argon2Verify, Algorithm, Version } from '@node-rs/argon2';
import { performance } from 'node:perf_hooks';

/**
 * Standard Argon2 hashing options
 * @typedef {Object} Argon2Options
 * @property {'argon2id'|'argon2i'|'argon2d'} [algorithm='argon2id'] Argon2 variant
 * @property {number} [memoryCost=65536] Memory in KiB (default: 64 MiB)
 * @property {number} [timeCost=3] Iteration count
 * @property {number} [parallelism=1] Number of threads / lanes
 * @property {number} [outputLen=32] Desired hash output length in bytes
 */

const ALGO_MAP = {
  argon2id: Algorithm.Argon2id,
  argon2i: Algorithm.Argon2i,
  argon2d: Algorithm.Argon2d,
};

/**
 * Hash a secret using Argon2
 * Compatible with PHP >= 8.2 (PASSWORD_ARGON2ID / PASSWORD_ARGON2I) and Python argon2-cffi.
 *
 * @param {string|Buffer} secret - The secret text to hash
 * @param {Argon2Options} [options={}] - Hashing parameters
 * @returns {Promise<{ hash: string, algorithm: string, executionTimeMs: number, parameters: object }>}
 */
export async function hashArgon2(secret, options = {}) {
  if (secret === undefined || secret === null) {
    throw new TypeError('Secret input is required for Argon2 hashing');
  }

  const variant = (options.algorithm || 'argon2id').toLowerCase();
  const algoEnum = ALGO_MAP[variant];
  if (algoEnum === undefined) {
    throw new Error(`Unsupported Argon2 algorithm: ${options.algorithm}. Use 'argon2id', 'argon2i', or 'argon2d'.`);
  }

  const memoryCost = Number(options.memoryCost ?? 65536);
  const timeCost = Number(options.timeCost ?? 3);
  const parallelism = Number(options.parallelism ?? 1);
  const outputLen = Number(options.outputLen ?? 32);

  if (isNaN(memoryCost) || memoryCost < 8) {
    throw new RangeError('Argon2 memoryCost must be at least 8 KiB');
  }
  if (isNaN(timeCost) || timeCost < 1) {
    throw new RangeError('Argon2 timeCost must be at least 1 iteration');
  }
  if (isNaN(parallelism) || parallelism < 1) {
    throw new RangeError('Argon2 parallelism must be at least 1 thread');
  }

  const startTime = performance.now();
  const hashString = await argon2Hash(secret, {
    algorithm: algoEnum,
    version: Version.Version13,
    memoryCost,
    timeCost,
    parallelism,
    outputLen,
  });
  const executionTimeMs = Number((performance.now() - startTime).toFixed(2));

  return {
    hash: hashString,
    algorithm: variant,
    executionTimeMs,
    parameters: {
      memoryCost,
      timeCost,
      parallelism,
      outputLen,
      version: 19, // 0x13
    },
  };
}

/**
 * Verify a secret against an Argon2 hash string
 * Compatible with hashes generated by PHP, Python, and Node.js.
 *
 * @param {string|Buffer} secret - The secret to verify
 * @param {string} hashString - The Argon2 Modular Crypt Format string
 * @returns {Promise<boolean>}
 */
export async function verifyArgon2(secret, hashString) {
  if (!secret || !hashString || typeof hashString !== 'string') {
    return false;
  }

  if (!hashString.startsWith('$argon2id$') && !hashString.startsWith('$argon2i$') && !hashString.startsWith('$argon2d$')) {
    return false;
  }

  try {
    return await argon2Verify(hashString, secret);
  } catch {
    return false;
  }
}
